#!/bin/bash
cd /data/Tbulleri/STACKSv2.41_outputs/ustacks_test/ustacksM1m8
ustacks -f /data/Tbulleri/process_radtags/N1.fq.gz -i 01 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N2.fq.gz -i 02 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N3.fq.gz -i 03 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N4.fq.gz -i 04 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N5.fq.gz -i 05 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N6.fq.gz -i 06 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N7.fq.gz -i 07 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N8.fq.gz -i 08 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N9.fq.gz -i 09 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N10.fq.gz -i 10 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N11.fq.gz -i 11 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N13.fq.gz -i 12 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N14.fq.gz -i 13 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N30.fq.gz -i 14 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N16.fq.gz -i 15 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N17.fq.gz -i 16 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N18.fq.gz -i 17 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N19.fq.gz -i 18 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N20.fq.gz -i 19 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N22.fq.gz -i 20 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N23.fq.gz -i 21 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N24.fq.gz -i 22 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N25.fq.gz -i 23 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N26.fq.gz -i 24 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N27.fq.gz -i 25 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N28.fq.gz -i 26 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N30.fq.gz -i 27 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N31.fq.gz -i 28 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S1.fq.gz -i 29 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S2.fq.gz -i 30 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S3.fq.gz -i 31 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S4.fq.gz -i 32 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S5.fq.gz -i 33 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S6.fq.gz -i 34 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S7.fq.gz -i 35 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S8.fq.gz -i 36 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S9.fq.gz -i 37 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S10.fq.gz -i 38 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S11.fq.gz -i 39 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S30.fq.gz -i 40 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S16.fq.gz -i 41 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S17.fq.gz -i 42 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S18.fq.gz -i 43 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S19.fq.gz -i 44 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S20.fq.gz -i 45 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S22.fq.gz -i 46 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S24.fq.gz -i 47 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S25.fq.gz -i 48 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S26.fq.gz -i 49 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S27.fq.gz -i 50 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S28.fq.gz -i 51 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S29.fq.gz -i 52 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S30.fq.gz -i 53 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S32.fq.gz -i 54 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S33.fq.gz -i 55 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S34.fq.gz -i 56 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S35.fq.gz -i 57 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S36.fq.gz -i 58 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S37.fq.gz -i 59 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S38.fq.gz -i 60 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S40.fq.gz -i 61 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S41.fq.gz -i 62 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S42.fq.gz -i 63 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S44.fq.gz -i 64 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S45.fq.gz -i 65 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S46.fq.gz -i 66 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S47.fq.gz -i 67 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S49.fq.gz -i 68 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S50.fq.gz -i 69 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S51.fq.gz -i 70 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S52.fq.gz -i 71 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S53.fq.gz -i 72 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S54.fq.gz -i 73 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S56.fq.gz -i 74 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S58.fq.gz -i 75 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S59.fq.gz -i 76 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S60.fq.gz -i 77 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S63.fq.gz -i 78 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S66.fq.gz -i 79 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S67.fq.gz -i 80 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S68.fq.gz -i 81 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S70.fq.gz -i 82 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S71.fq.gz -i 83 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S72.fq.gz -i 84 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S73.fq.gz -i 85 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S74.fq.gz -i 86 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S75.fq.gz -i 87 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S76.fq.gz -i 88 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S12.fq.gz -i 89 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S23.fq.gz -i 90 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S31.fq.gz -i 91 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S39.fq.gz -i 92 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S48.fq.gz -i 93 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S57.fq.gz -i 94 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S69.fq.gz -i 95 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/GBSNEG.fq.gz -i 96 -o ./ -M 1 -m 8 -p 30 -d --disable-gapped