#!/bin/bash
cd /data/Tbulleri/ustacks/ustacksM4m7

ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N5.trimmed.cropped.gz -i 1 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N8.trimmed.cropped.gz -i 2 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N9.trimmed.cropped.gz -i 3 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N10.trimmed.cropped.gz -i 4 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N11.trimmed.cropped.gz -i 5 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N13.trimmed.cropped.gz -i 6 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N14.trimmed.cropped.gz -i 7 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N15.trimmed.cropped.gz -i 8 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N17.trimmed.cropped.gz -i 9 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N18.trimmed.cropped.gz -i 10 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N19.trimmed.cropped.gz -i 11 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N20.trimmed.cropped.gz -i 12 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N22.trimmed.cropped.gz -i 13 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N23.trimmed.cropped.gz -i 14 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N24.trimmed.cropped.gz -i 15 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N26.trimmed.cropped.gz -i 16 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N28.trimmed.cropped.gz -i 17 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/N31.trimmed.cropped.gz -i 18 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S1.trimmed.cropped.gz -i 19 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S2.trimmed.cropped.gz -i 20 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S3.trimmed.cropped.gz -i 21 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S4.trimmed.cropped.gz -i 22 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S5.trimmed.cropped.gz -i 23 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S7.trimmed.cropped.gz -i 24 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S8.trimmed.cropped.gz -i 25 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S9.trimmed.cropped.gz -i 26 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S10.trimmed.cropped.gz -i 27 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S11.trimmed.cropped.gz -i 28 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S12.trimmed.cropped.gz -i 29 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S15.trimmed.cropped.gz -i 30 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S16.trimmed.cropped.gz -i 31 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S17.trimmed.cropped.gz -i 32 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S18.trimmed.cropped.gz -i 33 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S19.trimmed.cropped.gz -i 34 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S20.trimmed.cropped.gz -i 35 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S24.trimmed.cropped.gz -i 36 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S25.trimmed.cropped.gz -i 37 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S27.trimmed.cropped.gz -i 38 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S30.trimmed.cropped.gz -i 39 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S31.trimmed.cropped.gz -i 40 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S32.trimmed.cropped.gz -i 41 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S34.trimmed.cropped.gz -i 42 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S35.trimmed.cropped.gz -i 43 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S36.trimmed.cropped.gz -i 44 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S37.trimmed.cropped.gz -i 45 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S38.trimmed.cropped.gz -i 46 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S39.trimmed.cropped.gz -i 47 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S40.trimmed.cropped.gz -i 48 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S41.trimmed.cropped.gz -i 49 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S42.trimmed.cropped.gz -i 50 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S44.trimmed.cropped.gz -i 51 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S45.trimmed.cropped.gz -i 52 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S47.trimmed.cropped.gz -i 53 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S49.trimmed.cropped.gz -i 54 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S50.trimmed.cropped.gz -i 55 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S51.trimmed.cropped.gz -i 56 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S52.trimmed.cropped.gz -i 57 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S53.trimmed.cropped.gz -i 58 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S54.trimmed.cropped.gz -i 59 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S56.trimmed.cropped.gz -i 60 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S57.trimmed.cropped.gz -i 61 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S58.trimmed.cropped.gz -i 62 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S59.trimmed.cropped.gz -i 63 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S60.trimmed.cropped.gz -i 64 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S67.trimmed.cropped.gz -i 65 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S68.trimmed.cropped.gz -i 66 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S69.trimmed.cropped.gz -i 67 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S70.trimmed.cropped.gz -i 68 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S71.trimmed.cropped.gz -i 69 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S72.trimmed.cropped.gz -i 70 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S73.trimmed.cropped.gz -i 71 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S74.trimmed.cropped.gz -i 72 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S75.trimmed.cropped.gz -i 73 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/S76.trimmed.cropped.gz -i 74 -o ./ -M 4 -m 7 -p 30 -d -H &&
ustacks -f /data/Tbulleri/trimmed_cropped_radtags2/GBSNEG.trimmed.cropped.gz -i 75 -o ./ -M 4 -m 7 -p 30 -d -H
