#!/bin/bash
cd /data/Tbulleri/ustacks/ustacksM2m3

ustacks -f /data/Tbulleri/process_cropped_radtags2/N5.cropped.fq.gz -i 1 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N8.cropped.fq.gz -i 2 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N9.cropped.fq.gz -i 3 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N10.cropped.fq.gz -i 4 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N11.cropped.fq.gz -i 5 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N13.cropped.fq.gz -i 6 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N14.cropped.fq.gz -i 7 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N15.cropped.fq.gz -i 8 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N17.cropped.fq.gz -i 9 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N18.cropped.fq.gz -i 10 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N19.cropped.fq.gz -i 11 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N20.cropped.fq.gz -i 12 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N22.cropped.fq.gz -i 13 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N23.cropped.fq.gz -i 14 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N24.cropped.fq.gz -i 15 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N26.cropped.fq.gz -i 16 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N28.cropped.fq.gz -i 17 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/N31.cropped.fq.gz -i 18 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S1.cropped.fq.gz -i 19 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S2.cropped.fq.gz -i 20 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S3.cropped.fq.gz -i 21 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S4.cropped.fq.gz -i 22 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S5.cropped.fq.gz -i 23 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S7.cropped.fq.gz -i 24 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S8.cropped.fq.gz -i 25 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S9.cropped.fq.gz -i 26 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S10.cropped.fq.gz -i 27 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S11.cropped.fq.gz -i 28 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S12.cropped.fq.gz -i 29 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S15.cropped.fq.gz -i 30 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S16.cropped.fq.gz -i 31 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S17.cropped.fq.gz -i 32 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S18.cropped.fq.gz -i 33 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S19.cropped.fq.gz -i 34 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S20.cropped.fq.gz -i 35 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S24.cropped.fq.gz -i 36 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S25.cropped.fq.gz -i 37 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S27.cropped.fq.gz -i 38 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S30.cropped.fq.gz -i 39 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S31.cropped.fq.gz -i 40 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S32.cropped.fq.gz -i 41 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S34.cropped.fq.gz -i 42 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S35.cropped.fq.gz -i 43 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S36.cropped.fq.gz -i 44 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S37.cropped.fq.gz -i 45 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S38.cropped.fq.gz -i 46 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S39.cropped.fq.gz -i 47 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S40.cropped.fq.gz -i 48 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S41.cropped.fq.gz -i 49 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S42.cropped.fq.gz -i 50 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S44.cropped.fq.gz -i 51 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S45.cropped.fq.gz -i 52 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S47.cropped.fq.gz -i 53 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S49.cropped.fq.gz -i 54 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S50.cropped.fq.gz -i 55 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S51.cropped.fq.gz -i 56 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S52.cropped.fq.gz -i 57 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S53.cropped.fq.gz -i 58 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S54.cropped.fq.gz -i 59 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S56.cropped.fq.gz -i 60 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S57.cropped.fq.gz -i 61 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S58.cropped.fq.gz -i 62 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S59.cropped.fq.gz -i 63 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S60.cropped.fq.gz -i 64 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S67.cropped.fq.gz -i 65 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S68.cropped.fq.gz -i 66 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S69.cropped.fq.gz -i 67 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S70.cropped.fq.gz -i 68 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S71.cropped.fq.gz -i 69 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S72.cropped.fq.gz -i 70 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S73.cropped.fq.gz -i 71 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S74.cropped.fq.gz -i 72 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S75.cropped.fq.gz -i 73 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/S76.cropped.fq.gz -i 74 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_cropped_radtags2/GBSNEG.cropped.fq.gz -i 75 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped