#!/bin/bash
cd /data/Tbulleri/STACKSv2.41_outputs/ustacks_test/ustacksM2m3

ustacks -f /data/Tbulleri/process_radtags/N5.fq.gz -i 05 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N9.fq.gz -i 09 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N10.fq.gz -i 10 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N11.fq.gz -i 11 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N14.fq.gz -i 13 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N17.fq.gz -i 16 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N18.fq.gz -i 17 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N19.fq.gz -i 18 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N20.fq.gz -i 19 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N22.fq.gz -i 20 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N23.fq.gz -i 21 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N24.fq.gz -i 22 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N26.fq.gz -i 24 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/N31.fq.gz -i 28 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S2.fq.gz -i 30 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S4.fq.gz -i 32 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S5.fq.gz -i 33 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S8.fq.gz -i 36 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S9.fq.gz -i 37 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S11.fq.gz -i 39 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S12.fq.gz -i 40 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S16.fq.gz -i 41 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S18.fq.gz -i 43 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S19.fq.gz -i 44 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S20.fq.gz -i 45 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S24.fq.gz -i 47 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S25.fq.gz -i 48 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S27.fq.gz -i 50 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S32.fq.gz -i 54 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S34.fq.gz -i 56 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S36.fq.gz -i 58 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S37.fq.gz -i 59 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S38.fq.gz -i 57 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S39.fq.gz -i 60 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S40.fq.gz -i 61 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S41.fq.gz -i 62 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S42.fq.gz -i 63 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S44.fq.gz -i 64 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S45.fq.gz -i 65 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S47.fq.gz -i 67 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S50.fq.gz -i 69 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S51.fq.gz -i 70 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S52.fq.gz -i 71 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S53.fq.gz -i 72 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S54.fq.gz -i 73 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S57.fq.gz -i 74 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S67.fq.gz -i 80 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S68.fq.gz -i 81 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S69.fq.gz -i 83 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S70.fq.gz -i 82 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S72.fq.gz -i 84 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S73.fq.gz -i 85 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S74.fq.gz -i 86 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S75.fq.gz -i 87 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/S76.fq.gz -i 88 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped &&
ustacks -f /data/Tbulleri/process_radtags/GBSNEG.fq.gz -i 96 -o ./ -M 2 -m 3 -p 30 -d --disable-gapped